// Generated by scripts/generate-blocklists.mjs — do not edit by hand.
// Source of truth: src/data/ai-services.json

enum RulePackData {
    static let version = "2026.06.11"
    static let updatedAt = "2026-06-11"

    static let categories: [RuleCategory] = [
        RuleCategory(
            id: "chat",
            name: "AI Chat",
            symbol: "sparkles",
            colorHex: 0x0f9f8f,
            services: [
                RuleService(name: "OpenAI ChatGPT", domains: ["chatgpt.com", "chat.openai.com", "openai.com", "oaistatic.com", "oaiusercontent.com"]),
                RuleService(name: "Anthropic Claude", domains: ["claude.ai", "console.anthropic.com", "anthropic.com"]),
                RuleService(name: "Google Gemini", domains: ["gemini.google.com", "bard.google.com", "aistudio.google.com", "notebooklm.google.com"]),
                RuleService(name: "Meta AI", domains: ["meta.ai", "ai.meta.com"]),
                RuleService(name: "DeepSeek", domains: ["deepseek.com", "chat.deepseek.com"]),
                RuleService(name: "Qwen", domains: ["qwen.ai", "chat.qwen.ai"]),
                RuleService(name: "Kimi", domains: ["kimi.com", "moonshot.ai"]),
                RuleService(name: "Poe", domains: ["poe.com"]),
                RuleService(name: "Character.AI", domains: ["character.ai", "beta.character.ai"]),
                RuleService(name: "Pi", domains: ["pi.ai", "inflection.ai"]),
                RuleService(name: "Manus", domains: ["manus.im"]),
                RuleService(name: "Janitor AI", domains: ["janitorai.com"]),
                RuleService(name: "QuillBot", domains: ["quillbot.com"]),
                RuleService(name: "Grammarly", domains: ["grammarly.com", "app.grammarly.com"], strictOnly: true)
            ]
        ),
        RuleCategory(
            id: "search",
            name: "AI Search",
            symbol: "magnifyingglass",
            colorHex: 0xe49b29,
            services: [
                RuleService(name: "Perplexity", domains: ["perplexity.ai", "www.perplexity.ai"]),
                RuleService(name: "Microsoft Copilot", domains: ["copilot.microsoft.com", "bing.com", "edgeservices.bing.com"]),
                RuleService(name: "You.com", domains: ["you.com", "youcdn.io"]),
                RuleService(name: "Phind", domains: ["phind.com"]),
                RuleService(name: "Grok", domains: ["grok.com", "x.ai"]),
                RuleService(name: "Genspark", domains: ["genspark.ai"]),
                RuleService(name: "Andi", domains: ["andisearch.com"]),
                RuleService(name: "iAsk", domains: ["iask.ai"]),
                RuleService(name: "Komo", domains: ["komo.ai"])
            ]
        ),
        RuleCategory(
            id: "coding",
            name: "AI Coding",
            symbol: "curlybraces",
            colorHex: 0x5967d8,
            services: [
                RuleService(name: "GitHub Copilot", domains: ["githubcopilot.com", "api.githubcopilot.com", "copilot-proxy.githubusercontent.com"]),
                RuleService(name: "Cursor", domains: ["cursor.com", "api2.cursor.sh", "cursor.sh"]),
                RuleService(name: "Replit AI", domains: ["replit.com", "replit.ai"]),
                RuleService(name: "Blackbox AI", domains: ["blackbox.ai", "www.blackbox.ai"]),
                RuleService(name: "Codeium Windsurf", domains: ["codeium.com", "windsurf.com"]),
                RuleService(name: "Lovable", domains: ["lovable.dev", "lovable.app"]),
                RuleService(name: "Bolt", domains: ["bolt.new"]),
                RuleService(name: "v0", domains: ["v0.dev", "v0.app"]),
                RuleService(name: "Devin", domains: ["devin.ai", "cognition.ai"]),
                RuleService(name: "Tabnine", domains: ["tabnine.com", "api.tabnine.com"]),
                RuleService(name: "Augment Code", domains: ["augmentcode.com"]),
                RuleService(name: "Sourcegraph Cody", domains: ["sourcegraph.com"], strictOnly: true)
            ]
        ),
        RuleCategory(
            id: "creative",
            name: "Image/Video AI",
            symbol: "wand.and.stars",
            colorHex: 0xce4f4f,
            services: [
                RuleService(name: "Midjourney", domains: ["midjourney.com", "www.midjourney.com"]),
                RuleService(name: "OpenAI Sora", domains: ["sora.com"]),
                RuleService(name: "Runway", domains: ["runwayml.com", "app.runwayml.com"]),
                RuleService(name: "Luma", domains: ["lumalabs.ai"]),
                RuleService(name: "Pika", domains: ["pika.art"]),
                RuleService(name: "Kling", domains: ["klingai.com"]),
                RuleService(name: "Hailuo", domains: ["hailuoai.video", "minimax.io"]),
                RuleService(name: "HeyGen", domains: ["heygen.com", "app.heygen.com"]),
                RuleService(name: "Stability AI", domains: ["stability.ai", "platform.stability.ai"]),
                RuleService(name: "Black Forest Labs", domains: ["bfl.ai"]),
                RuleService(name: "Leonardo AI", domains: ["leonardo.ai", "app.leonardo.ai"]),
                RuleService(name: "Ideogram", domains: ["ideogram.ai"]),
                RuleService(name: "Krea", domains: ["krea.ai"]),
                RuleService(name: "Recraft", domains: ["recraft.ai"]),
                RuleService(name: "Civitai", domains: ["civitai.com"]),
                RuleService(name: "Adobe Firefly", domains: ["firefly.adobe.com"]),
                RuleService(name: "Google Labs", domains: ["labs.google"]),
                RuleService(name: "Suno", domains: ["suno.com", "suno.ai"]),
                RuleService(name: "Udio", domains: ["udio.com"]),
                RuleService(name: "ElevenLabs", domains: ["elevenlabs.io", "api.elevenlabs.io"])
            ]
        ),
        RuleCategory(
            id: "api",
            name: "AI APIs",
            symbol: "globe",
            colorHex: 0x1482a5,
            services: [
                RuleService(name: "OpenAI API", domains: ["api.openai.com", "platform.openai.com"]),
                RuleService(name: "Anthropic API", domains: ["api.anthropic.com"]),
                RuleService(name: "Google AI API", domains: ["generativelanguage.googleapis.com", "ai.google.dev"]),
                RuleService(name: "Azure OpenAI", domains: ["openai.azure.com"]),
                RuleService(name: "xAI API", domains: ["api.x.ai"]),
                RuleService(name: "DeepSeek API", domains: ["api.deepseek.com", "platform.deepseek.com"]),
                RuleService(name: "Mistral AI", domains: ["mistral.ai", "chat.mistral.ai", "api.mistral.ai", "console.mistral.ai"]),
                RuleService(name: "Cohere", domains: ["cohere.com", "api.cohere.com"]),
                RuleService(name: "Groq", domains: ["groq.com", "api.groq.com"]),
                RuleService(name: "Together AI", domains: ["together.ai", "api.together.xyz"]),
                RuleService(name: "Fireworks AI", domains: ["fireworks.ai", "api.fireworks.ai"]),
                RuleService(name: "Cerebras", domains: ["cerebras.ai", "api.cerebras.ai"]),
                RuleService(name: "OpenRouter", domains: ["openrouter.ai"]),
                RuleService(name: "Replicate", domains: ["replicate.com", "api.replicate.com"]),
                RuleService(name: "Google Vertex AI", domains: ["aiplatform.googleapis.com"], strictOnly: true),
                RuleService(name: "Hugging Face", domains: ["huggingface.co", "api-inference.huggingface.co"], strictOnly: true),
                RuleService(name: "Ollama", domains: ["ollama.com"], strictOnly: true),
                RuleService(name: "LM Studio", domains: ["lmstudio.ai"], strictOnly: true)
            ]
        )
    ]
}
